apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- allowedrepos
- automount-serviceaccount-token
- block-endpoint-edit-default-role
- block-loadbalancer-services
- block-nodeport-services
- block-wildcard-ingress
- containerresources
- disallowanonymous
- disallowedrepos
- disallowedtags
- disallowinteractive
- externalip
- httpsonly
- imagedigests
- poddisruptionbudget
- requiredimagepullsecrets
- requiredlabels
- uniqueingresshost